CREATE TABLE `role` (
  `type`    VARCHAR(255) NOT NULL,
  `actions` LONGTEXT     NOT NULL,
  PRIMARY KEY (`type`)
);

INSERT INTO `role` (`type`, `actions`)
VALUES ('SUPER_ADMIN',
        'CREATE_OR_UPDATE_DOCTORS_AS_ADMIN,DELETE_DOCTORS,SHOW_PATIENTS,UPDATE_PATIENTS,DELETE_PATIENTS,ROLES,SHOW_SPECIALTIES,CREATE_SPECIALTIES,UPDATE_SPECIALTIES,DELETE_SPECIALTIES,ADMINS,SHOW_APPOINTMENTS,CREATE_APPOINTMENTS,UPDATE_APPOINTMENTS,DELETE_APPOINTMENTS');