package net.therap.onlinedoctorbookingmanagement.utilities.enums;

/**
 * @author anwar
 * @since 2/22/18
 */

public enum ROLE_ACTIONS {

    CREATE_OR_UPDATE_DOCTORS_AS_ADMIN,
    UPDATE_PROFILE_FOR_DOCTOR,
    DELETE_DOCTORS,
    SHOW_PATIENTS,
    UPDATE_PATIENTS,
    UPDATE_PROFILE_FOR_PATIENT,
    DELETE_PATIENTS,
    SHOW_SPECIALTIES,
    CREATE_SPECIALTIES,
    UPDATE_SPECIALTIES,
    DELETE_SPECIALTIES,
    SHOW_APPOINTMENTS,
    SHOW_MY_APPOINTMENTS,
    CREATE_APPOINTMENTS,
    CREATE_MY_APPOINTMENTS,
    UPDATE_APPOINTMENTS,
    UPDATE_MY_APPOINTMENTS,
    DELETE_APPOINTMENTS,
    DELETE_MY_APPOINTMENTS,
    ADMINS,
    ROLES
}